; LS ESP32 Pro + LT-20W-A alignment frame
; Generated by Codex Laser Engraver
G21
G90
G94
M5
; Dry motion frame. No laser power is emitted.
M5
G0 X10.000 Y10.000
G0 X90.000 Y10.000 F2500
G0 X90.000 Y60.000 F2500
G0 X10.000 Y60.000 F2500
G0 X10.000 Y10.000 F2500
M5
M9
G0 X0 Y0
; End
